### PR TITLE
Big fixes

### PR DESCRIPTION
**Pull request by jag-k**
Changelog:

- Added dev-dependencies
- Added loggers
- Added auto-creating collections, if there is not exists
- Added async support (using `motor` lib)
- Fix some issues while saving
- Reformat files
- Little changes in README.md

### CODE REVIEW

**Comment by jag-k** [comment]
@LucaSforza yea, I know, this is a lot of changes, but if you need to explanation, I can explain all of them 😄 

I tested these changes on my "big" bot and all work perfectly!

**Comment by LucaSforza** [comment]
@jag-k Thank you so much for contributing to my project.
It doesn't matter if you've made so many changes, I'm a beginner and I'm only in my first year of computer science at university so you were right to correct all my coding horrors.
However, yes indeed I have many questions and I apologize in advance if some may seem trivial.

first of all on line 80 of the code I get this error:

```
2023-04-12 22:32:28,147 - persistence - INFO - Getting collection 'user-data'...
Traceback (most recent call last):
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/test_bot.py", line 118, in <module>
    main()
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/test_bot.py", line 114, in main
    application.run_polling()
  File "/Users/lucasforza/Library/Caches/pypoetry/virtualenvs/mongopersistence-QtoYStFY-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 725, in run_polling
    return self.__run(
  File "/Users/lucasforza/Library/Caches/pypoetry/virtualenvs/mongopersistence-QtoYStFY-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 919, in __run
    raise exc
  File "/Users/lucasforza/Library/Caches/pypoetry/virtualenvs/mongopersistence-QtoYStFY-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 908, in __run
    loop.run_until_complete(self.initialize())
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/lucasforza/Library/Caches/pypoetry/virtualenvs/mongopersistence-QtoYStFY-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 405, in initialize
    await self._initialize_persistence()
  File "/Users/lucasforza/Library/Caches/pypoetry/virtualenvs/mongopersistence-QtoYStFY-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 485, in _initialize_persistence
    self._user_data.update(await self.persistence.get_user_data())
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/persistence.py", line 35, in wrapper
    res = await func(self, *args, **kwargs)
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/persistence.py", line 233, in get_user_data
    return await self.get_data(self.user_data)
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/persistence.py", line 173, in get_data
    await self.post_init()
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/persistence.py", line 158, in post_init
    await self.user_data.post_init()
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/persistence.py", line 80, in post_init
    self.col = await self.db.get_collection(self.collection_name)
TypeError: object AsyncIOMotorCollection can't be used in 'await' expression
(mongopersistence-py3.10) lucasforza mongopersistence $ python test_bot.py
2023-04-13 08:17:08,232 - persistence - INFO - Getting collection 'user-data'...
Traceback (most recent call last):
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/test_bot.py", line 118, in <module>
    main()
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/test_bot.py", line 114, in main
    application.run_polling()
  File "/Users/lucasforza/Library/Caches/pypoetry/virtualenvs/mongopersistence-QtoYStFY-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 725, in run_polling
    return self.__run(
  File "/Users/lucasforza/Library/Caches/pypoetry/virtualenvs/mongopersistence-QtoYStFY-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 919, in __run
    raise exc
  File "/Users/lucasforza/Library/Caches/pypoetry/virtualenvs/mongopersistence-QtoYStFY-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 908, in __run
    loop.run_until_complete(self.initialize())
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/lucasforza/Library/Caches/pypoetry/virtualenvs/mongopersistence-QtoYStFY-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 405, in initialize
    await self._initialize_persistence()
  File "/Users/lucasforza/Library/Caches/pypoetry/virtualenvs/mongopersistence-QtoYStFY-py3.10/lib/python3.10/site-packages/telegram/ext/_application.py", line 485, in _initialize_persistence
    self._user_data.update(await self.persistence.get_user_data())
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/persistence.py", line 35, in wrapper
    res = await func(self, *args, **kwargs)
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/persistence.py", line 233, in get_user_data
    return await self.get_data(self.user_data)
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/persistence.py", line 173, in get_data
    await self.post_init()
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/persistence.py", line 158, in post_init
    await self.user_data.post_init()
  File "/Users/lucasforza/Documents/contribution/MongoPersistence/mongopersistence/persistence.py", line 80, in post_init
    self.col = await self.db.get_collection(self.collection_name)
TypeError: object AsyncIOMotorCollection can't be used in 'await' expression
```

i tried your version of MongoPersistence in this bot

```python
import logging
import costants as keys
from persistence import MongoPersistence

from telegram import __version__ as TG_VER

try:
    from telegram import __version_info__
except ImportError:
    __version_info__ = (0, 0, 0, 0, 0)  # type: ignore[assignment]

if __version_info__ < (20, 0, 0, "alpha", 1):
    raise RuntimeError(
        f"This example is not compatible with your current PTB version {TG_VER}. To view the "
        f"{TG_VER} version of this example, "
        f"visit https://docs.python-telegram-bot.org/en/v{TG_VER}/examples.html"
    )
from telegram import ForceReply, Update
from telegram.ext import Application, CommandHandler, ContextTypes, MessageHandler, filters

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
logger = logging.getLogger(__name__)

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Send a message when the command /start is issued."""
    user = update.effective_user
    await update.message.reply_html(
        rf"Hi {user.mention_html()}!",
        reply_markup=ForceReply(selective=True),
    )
    
async def insert(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    chat_id   = update.effective_chat.id
    user_data = context.user_data
    chat_data = context.chat_data
    bot_data  = context.bot_data
    
    def string_to_tuple(string: str) -> tuple:
        string = string.replace('(','')
        string = string.replace(')','')
        return tuple(string.split(','))
    
    args = update.message.text.split()[1]
    key,content = string_to_tuple(args)
    user_data[key] = content
    
    await context.bot.send_message(chat_id,user_data)

async def data(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    chat_id   = update.effective_chat.id
    user_data = context.user_data
    chat_data = context.chat_data
    bot_data  = context.bot_data
    
    await context.bot.send_message(chat_id,f"{user_data},{chat_data},{bot_data}")

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text("Help!")

async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(update.message.text)


def main() -> None:
    mongodb = MongoPersistence(
        keys.MONGO_KEY,
        keys.DB_NAME,
        name_col_user_data=keys.COLLECTION_NAME,
        load_on_flush=True,
        ignore_general_data=['cache'],
        update_interval=1
    )
    
    application = Application.builder().token(keys.API_KEY).persistence(mongodb).build()

    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("help", help_command))
    application.add_handler(CommandHandler("data",data))
    application.add_handler(CommandHandler("insert",insert))

    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, echo))
    application.run_polling()

if __name__ == "__main__":
    main()
```

but if I remove that await in that line of code then everything actually works

Other than that I have other questions:
The first question is why both in the MongoPersistence class and in TypeData an async post_init method has been defined which is executed every time a method like for example get_data is called

The second question is why in the refresh_data method the update_data method is called and the code that was there before has been removed, the first thing I thought was that it was done because maybe I misunderstood how these methods should be implemented, but in the python telegram bot documentation I haven't found enough explanation how they should be implemented.
As I understand it update_data should update the database with the data that is in our bot.
Instead on refresh_data the bot data had to be updated from those in the database.
At least that's what I read from the documentation.
In fact, with your code, if I modify a data with a foreign application to the bot connected to the same database then it is not updated in my telegram bot, things that when I started this project were my first goal, so I think I will then have to modify that part of the code later.

The third question is why the update_bot_data method was called on refresh_bot_data
Indeed then you recreate the same problem described in the question before.

Then I don't think load_on_flush=True works, because by testing it once I close the bot the data are not updated in the database

Thanks in advance for the clarifications.

**Comment by jag-k** [comment]
Oh, yea. I think I know how to fix this issues, but I'm working now. I'll fix this a little bit later

**Comment by LucaSforza** [comment]
Thanks a lot, no problem

**Comment by jag-k** [comment]
My answers:

1. Yea, this `await` is unnecessary. I'm remove this.
2. This `post_init` needs to be create Collections, if they doesn't exist. No worry, it be called once. (hack with `_inited`)
3. Yes, you correctly understood the principle of operation of these methods, but in Python it is quite problematic to compare dictionaries in this way. In any case, you will have to make a request to the database, so it's easier and more efficient to do an update right away
4. Hmm, I create a little fix, if `load_on_flush=True` doesn't work, please, let me know

**Comment by LucaSforza** [comment]
Okay, thanks @jag-k .
I found out that the reason why the data wasn't loading when `load_on_flush=True` and fixed it, really was my code problem not yours, so now just update your PR with the changes to make it compatible with main branch and I can merge your code.
Thanks again for contributing, it's the first time someone contributes to my project and I feel like I've learned a lot, a lot more than I can learn in college.

**Comment by jag-k** [comment]
@LucaSforza check it!

**Pull request merged**
